version: '2.2'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    container_name: elk
    environment:
      - 'discovery.type=single-node'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    logging:
      driver: 'json-file'
      options:
        max-file: '3'
        max-size: '500m'
    ports:
      - 9200:9200
      - 9300:9300
    network_mode: bridge
# docker run -d --name elk -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:7.3.0
